/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/accounts/auth/login/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login user
         * @description Authenticate user with email and password and return token and profile info.
         */
        post: operations["api_accounts_auth_login_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/auth/register/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create user account
         * @description Create a new user account and return an authentication token.
         */
        post: operations["api_accounts_auth_register_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/profile/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get user profile
         * @description Retrieve the authenticated user's profile, business, and bank details.
         */
        get: operations["api_accounts_profile_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/accounts/profile/update/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update personal details
         * @description Update merchant's personal profile information
         */
        patch: operations["api_accounts_profile_update_partial_update"];
        trace?: never;
    };
    "/api/accounts/profile/update-all/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update personal details and WhatsApp
         * @description Update both personal details and WhatsApp number in one request
         */
        patch: operations["api_accounts_profile_update_all_partial_update"];
        trace?: never;
    };
    "/api/accounts/profile/whatsapp/update/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update WhatsApp number
         * @description Update merchant's WhatsApp number
         */
        patch: operations["api_accounts_profile_whatsapp_update_partial_update"];
        trace?: never;
    };
    "/api/accounts/setup/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Complete account setup
         * @description Handles initial merchant account setup including:
         *     - Personal details
         *     - Business details
         *     - Bank details
         *     - WhatsApp contact
         *
         *     This endpoint must be completed before accessing protected merchant features.
         */
        patch: operations["api_accounts_setup_partial_update"];
        trace?: never;
    };
    "/api/accounts/store/link/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Get the logged-in user's unique store link */
        get: operations["api_accounts_store_link_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dispatch/delete/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["api_dispatch_delete_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dispatch/dispatch/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["api_dispatch_dispatch_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dispatch/list_update/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List or create dispatcher profile
         * @description Retrieve the dispatcher's profile if it exists, or create a new dispatcher profile.
         */
        get: operations["api_dispatch_list_update_retrieve"];
        put?: never;
        /**
         * List or create dispatcher profile
         * @description Retrieve the dispatcher's profile if it exists, or create a new dispatcher profile.
         */
        post: operations["api_dispatch_list_update_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/notifications/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get notifications
         * @description Get all notifications for the authenticated user. Can filter by type (order/product) and read status.
         */
        get: operations["api_notifications_notifications_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/notifications/{id}/delete/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete notification
         * @description Delete a specific notification by ID
         */
        delete: operations["api_notifications_notifications_delete_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/notifications/notifications/{id}/read/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Mark notification as read
         * @description Mark a single notification as read by ID
         */
        patch: operations["api_notifications_notifications_read_partial_update"];
        trace?: never;
    };
    "/api/notifications/notifications/read-all/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Mark all notifications as read
         * @description Mark all notifications as read for the authenticated user
         */
        patch: operations["api_notifications_notifications_read_all_partial_update"];
        trace?: never;
    };
    "/api/notifications/notifications/unread-count/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get unread count
         * @description Get the count of unread notifications for the authenticated user
         */
        get: operations["api_notifications_notifications_unread_count_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all merchant orders
         * @description Get all orders for the logged-in merchant with optional filters
         */
        get: operations["api_orders_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/{order_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get single order
         * @description Get details of a specific order
         */
        get: operations["api_orders_retrieve_2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/{order_id}/accept/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Accept order
         * @description Merchant accepts a pending order
         */
        patch: operations["api_orders_accept_partial_update"];
        trace?: never;
    };
    "/api/orders/{order_id}/assign-dispatcher/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Assign dispatcher to order
         * @description Assign a dispatcher to handle delivery
         */
        post: operations["api_orders_assign_dispatcher_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/{order_id}/decline/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Decline order
         * @description Merchant declines an accepted order
         */
        patch: operations["api_orders_decline_partial_update"];
        trace?: never;
    };
    "/api/orders/{order_id}/ship/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Mark order as shipped
         * @description Merchant marks an accepted order as shipped
         */
        patch: operations["api_orders_ship_partial_update"];
        trace?: never;
    };
    "/api/orders/{order_id}/unassign-dispatcher/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Unassign dispatcher
         * @description Remove dispatcher from order
         */
        post: operations["api_orders_unassign_dispatcher_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/{order_id}/update-status/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update order status
         * @description Update order status with validation
         */
        patch: operations["api_orders_update_status_partial_update"];
        trace?: never;
    };
    "/api/orders/accepted/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get accepted orders
         * @description Get all accepted orders (not yet shipped)
         */
        get: operations["api_orders_accepted_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/analytics/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get store analytics
         * @description Get monthly analytics: total sales, orders, and shipped orders
         */
        get: operations["api_orders_analytics_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/create/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create order (Customer - No auth)
         * @description Customer creates an order and receives WhatsApp link to contact merchant. Order is created with 'accepted' status.
         */
        post: operations["api_orders_create_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/declined/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get declined orders
         * @description Get all declined orders
         */
        get: operations["api_orders_declined_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/dispatcher/my-orders/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get dispatcher orders
         * @description Get orders assigned to logged-in dispatcher
         */
        get: operations["api_orders_dispatcher_my_orders_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/dispatchers/available/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get available dispatchers
         * @description Get list of available dispatchers
         */
        get: operations["api_orders_dispatchers_available_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/incoming/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get incoming/pending orders
         * @description Get all pending orders for the merchant
         */
        get: operations["api_orders_incoming_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/shipped/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get shipped orders
         * @description Get all shipped orders for the merchant
         */
        get: operations["api_orders_shipped_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/track/{order_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Track order (Public)
         * @description Track order status by order ID
         */
        get: operations["api_orders_track_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get single product
         * @description Get a product with all its images
         */
        get: operations["api_products_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/{id}/delete/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete product
         * @description Delete a product and all its images
         */
        delete: operations["api_products_delete_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/{id}/images/{image_id}/delete/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete product image
         * @description Delete a specific product image
         */
        delete: operations["api_products_images_delete_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/{id}/images/upload/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload/Update single image
         * @description Upload or update a single image for a specific position
         */
        post: operations["api_products_images_upload_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/{id}/toggle-archive/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Toggle archive product
         * @description Archive or unarchive a product
         */
        patch: operations["api_products_toggle_archive_partial_update"];
        trace?: never;
    };
    "/api/products/{id}/toggle-stock/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Toggle in_stock product
         * @description Set or unset a product as in stock
         */
        patch: operations["api_products_toggle_stock_partial_update"];
        trace?: never;
    };
    "/api/products/{id}/update/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update product
         * @description Update product details and optionally update images
         */
        patch: operations["api_products_update_partial_update"];
        trace?: never;
    };
    "/api/products/all_products/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get all products for the app
         * @description Public endpoint to get all products available in the app
         */
        get: operations["api_products_all_products_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/create/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create product with images
         * @description Create a new product with up to 4 images (front, back, left, right) in a single request
         */
        post: operations["api_products_create_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/featured/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get featured/latest products
         * @description Get the latest products across all merchants
         */
        get: operations["api_products_featured_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/list/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List user products
         * @description Returns a list of products belonging to the authenticated user.
         *
         *     **Filtering behavior:**
         *     - By default (`include_archived=false`): returns only active products
         *     - If `include_archived=true`: returns only archived products
         *
         *     If archived products are requested and none exist, a message is returned.
         */
        get: operations["api_products_list_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/search/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search all products (Public)
         * @description Search products across all merchants with filters
         */
        get: operations["api_products_search_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/search/store/{store_slug}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search products by store
         * @description Search products within a specific merchant's store
         */
        get: operations["api_products_search_store_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/suggestions/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get product suggestions
         * @description Get product suggestions based on search query (autocomplete)
         */
        get: operations["api_products_suggestions_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/schema/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description OpenApi3 schema for this API. Format can be selected via content negotiation.
         *
         *     - YAML: application/vnd.oai.openapi
         *     - JSON: application/vnd.oai.openapi+json
         */
        get: operations["api_schema_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/store/{store_slug}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get merchant public store
         * @description Retrieve a merchant's public store information and all active (non-archived) products. This endpoint is publicly accessible and does not require authentication.
         */
        get: operations["store_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/store/{store_slug}/{product_uuid}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get product by store slug and product UUID
         * @description Retrieve a product using the store's slug and the product's UUID (public endpoint)
         */
        get: operations["store_retrieve_2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Notification: {
            id: number;
            /** @enum {string} */
            type: "order" | "product";
            message: string;
            is_read: boolean;
            time?: string;
            time_ago?: string;
            /** Format: date-time */
            created_at?: string;
        };
        /** @description Serializer for assigning dispatcher to order */
        AssignDispatcher: {
            dispatcher_id: number;
            /** Format: decimal */
            delivery_fee?: string;
            merchant_notes?: string;
        };
        BankDetail: {
            bank_name: string;
            account_number: string;
        };
        BusinessDetails: {
            readonly store_url: string;
            business_name: string;
            business_description: string;
            /** Format: email */
            business_email: string;
            store_slug?: string;
        };
        CreateAccount: {
            /** Format: email */
            email: string;
            password: string;
            confirm_password: string;
        };
        /**
         * @description * `pickup` - PICKUP
         *     * `delivery` - DELIVERY
         * @enum {string}
         */
        DeliveryMethodEnum: "pickup" | "delivery";
        Dispatcher: {
            readonly id: number;
            name: string;
            phone_number: string;
            address: string;
            next_of_kin: string;
            /** Format: uri */
            utility_bill?: string | null;
            bank_name: string;
            account_number: string;
            account_name: string;
            vehicle_type: components["schemas"]["VehicleTypeEnum"];
            plate_number: string;
            location_area: string;
            peferred_transport_area: components["schemas"]["PeferredTransportAreaEnum"];
            is_available?: boolean;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
            readonly user: number;
        };
        Login: {
            /** Format: email */
            email: string;
            password: string;
        };
        Order: {
            readonly id: number;
            readonly merchant: number;
            /** Format: email */
            readonly merchant_email: string;
            product: number;
            readonly product_name: string;
            /** Format: decimal */
            readonly product_price: string;
            readonly product_details: components["schemas"]["Product"];
            customer_name: string;
            customer_address: string;
            customer_whatsapp: string;
            delivery_method: components["schemas"]["DeliveryMethodEnum"];
            /** Format: int64 */
            quantity?: number;
            /** Format: decimal */
            readonly total_price: string;
            readonly status: components["schemas"]["OrderStatusEnum"];
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
            /** Format: date-time */
            readonly accepted_at: string;
            /** Format: date-time */
            readonly shipped_at: string | null;
            /** Format: date-time */
            readonly declined_at: string | null;
        };
        /** @description Serializer for customers to create orders (no auth required) */
        OrderCreate: {
            product: number;
            customer_name: string;
            customer_address: string;
            customer_whatsapp: string;
            delivery_method: components["schemas"]["DeliveryMethodEnum"];
            /** Format: int64 */
            quantity?: number;
        };
        /**
         * @description * `pending` - Pending
         *     * `accepted` - Accepted
         *     * `assigned` - Assigned to Dispatcher
         *     * `picked_up` - Picked Up by Dispatcher
         *     * `in_transit` - In Transit
         *     * `delivered` - Delivered
         *     * `shipped` - Shipped
         *     * `declined` - Declined
         *     * `completed` - Completed
         *     * `cancelled` - Cancelled
         * @enum {string}
         */
        OrderStatusEnum: "pending" | "accepted" | "assigned" | "picked_up" | "in_transit" | "delivered" | "shipped" | "declined" | "completed" | "cancelled";
        /**
         * @description * `accepted` - accepted
         *     * `shipped` - shipped
         *     * `declined` - declined
         *     * `completed` - completed
         * @enum {string}
         */
        OrderStatusUpdateStatusEnum: "accepted" | "shipped" | "declined" | "completed";
        /** @description Serializer for merchants to update order status */
        PatchedOrderStatusUpdate: {
            status?: components["schemas"]["OrderStatusUpdateStatusEnum"];
            merchant_notes?: string;
        };
        /** @description Serializer for creating and updating products WITH images */
        PatchedProductCreateUpdate: {
            name?: string;
            /** Format: decimal */
            price?: string;
            description?: string;
            is_archived?: boolean;
            /** Format: uri */
            front_image?: string | null;
            /** Format: uri */
            back_image?: string | null;
            /** Format: uri */
            left_image?: string | null;
            /** Format: uri */
            right_image?: string | null;
        };
        /** @description Combined serializer for updating both profile and WhatsApp */
        PatchedProfileAndWhatsApp: {
            PersonalDetails?: components["schemas"]["ProfileUpdate"];
            WhatsApp?: components["schemas"]["WhatsAppUpdate"];
        };
        PatchedProfileUpdate: {
            full_name?: string;
            /** Format: uri */
            display_picture?: string | null;
            readonly display_picture_url?: string;
            username?: string;
            phone_number?: string;
            address?: string;
        };
        PatchedSetupAccount: {
            PersonalDetails?: components["schemas"]["Profile"];
            BusinessDetails?: components["schemas"]["BusinessDetails"];
            BankDetail?: components["schemas"]["BankDetail"];
            WhatsApp?: components["schemas"]["WhatsAppDetail"];
        };
        /** @description Serializer for updating WhatsApp number */
        PatchedWhatsAppUpdate: {
            whatsapp_number?: string;
        };
        /**
         * @description * `local` - Within located are only
         *     * `outside` - Outside located area only
         *     * `anywhere` - Anywhere is fine
         * @enum {string}
         */
        PeferredTransportAreaEnum: "local" | "outside" | "anywhere";
        /**
         * @description * `front` - Front
         *     * `back` - Back
         *     * `left` - Left
         *     * `right` - Right
         * @enum {string}
         */
        PositionEnum: "front" | "back" | "left" | "right";
        /** @description Complete product serializer with all images */
        Product: {
            readonly id: number;
            /** Format: uuid */
            readonly product_id: string;
            name: string;
            /** Format: decimal */
            price: string;
            description: string;
            readonly images: components["schemas"]["ProductImage"][];
            readonly primary_image: string;
            is_archived?: boolean;
            in_stock?: boolean;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
            /** Format: email */
            readonly owner_email: string;
            readonly product_url: string;
            readonly shareable_link: string;
            readonly store_slug: string;
        };
        /** @description Serializer for creating and updating products WITH images */
        ProductCreateUpdate: {
            name: string;
            /** Format: decimal */
            price: string;
            description: string;
            is_archived?: boolean;
            /** Format: uri */
            front_image?: string | null;
            /** Format: uri */
            back_image?: string | null;
            /** Format: uri */
            left_image?: string | null;
            /** Format: uri */
            right_image?: string | null;
        };
        /** @description Serializer for product images */
        ProductImage: {
            readonly id: number;
            /** Format: uri */
            image?: string | null;
            readonly image_url: string;
            position: components["schemas"]["PositionEnum"];
            /** Format: date-time */
            readonly created_at: string;
        };
        Profile: {
            full_name: string;
            /** Format: uri */
            display_picture?: string | null;
            username: string;
            phone_number: string;
            address: string;
        };
        ProfileUpdate: {
            full_name: string;
            /** Format: uri */
            display_picture?: string | null;
            readonly display_picture_url: string;
            username?: string;
            phone_number?: string;
            address: string;
        };
        /**
         * @description * `car` - CAR
         *     * `motorcycle` - MOTORCYCLE
         * @enum {string}
         */
        VehicleTypeEnum: "car" | "motorcycle";
        WhatsAppDetail: {
            whatsapp_number: string;
        };
        /** @description Serializer for updating WhatsApp number */
        WhatsAppUpdate: {
            whatsapp_number: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    api_accounts_auth_login_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Login"];
                "multipart/form-data": components["schemas"]["Login"];
                "application/x-www-form-urlencoded": components["schemas"]["Login"];
            };
        };
        responses: {
            /** @description Login successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_accounts_auth_register_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAccount"];
                "multipart/form-data": components["schemas"]["CreateAccount"];
                "application/x-www-form-urlencoded": components["schemas"]["CreateAccount"];
            };
        };
        responses: {
            /** @description Account created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_accounts_profile_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Profile retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Profile not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_accounts_profile_update_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["PatchedProfileUpdate"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedProfileUpdate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProfileUpdate"];
                };
            };
        };
    };
    api_accounts_profile_update_all_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["PatchedProfileAndWhatsApp"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedProfileAndWhatsApp"];
            };
        };
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_accounts_profile_whatsapp_update_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedWhatsAppUpdate"];
                "multipart/form-data": components["schemas"]["PatchedWhatsAppUpdate"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedWhatsAppUpdate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WhatsAppUpdate"];
                };
            };
        };
    };
    api_accounts_setup_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["PatchedSetupAccount"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedSetupAccount"];
            };
        };
        responses: {
            /** @description Account setup completed successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation errors */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Authentication required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_accounts_store_link_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_dispatch_delete_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_dispatch_dispatch_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_dispatch_list_update_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Dispatcher"];
                };
            };
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Dispatcher"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    api_dispatch_list_update_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Dispatcher"];
                "multipart/form-data": components["schemas"]["Dispatcher"];
                "application/x-www-form-urlencoded": components["schemas"]["Dispatcher"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Dispatcher"];
                };
            };
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Dispatcher"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    api_notifications_notifications_retrieve: {
        parameters: {
            query?: {
                /** @description Filter by notification type */
                type?: "order" | "product";
                /** @description Show only unread notifications */
                unread_only?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        notifications?: components["schemas"]["Notification"][];
                        unread_count?: number;
                    };
                };
            };
        };
    };
    api_notifications_notifications_delete_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success?: boolean;
                    };
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error?: string;
                    };
                };
            };
        };
    };
    api_notifications_notifications_read_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success?: boolean;
                    };
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error?: string;
                    };
                };
            };
        };
    };
    api_notifications_notifications_read_all_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success?: boolean;
                        updated_count?: number;
                    };
                };
            };
        };
    };
    api_notifications_notifications_unread_count_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        unread_count?: number;
                    };
                };
            };
        };
    };
    api_orders_retrieve: {
        parameters: {
            query?: {
                /** @description Filter by status: accepted, shipped, declined */
                status?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_orders_retrieve_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_orders_accept_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_orders_assign_dispatcher_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignDispatcher"];
                "multipart/form-data": components["schemas"]["AssignDispatcher"];
                "application/x-www-form-urlencoded": components["schemas"]["AssignDispatcher"];
            };
        };
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_orders_decline_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_orders_ship_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_orders_unassign_dispatcher_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_orders_update_status_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedOrderStatusUpdate"];
                "multipart/form-data": components["schemas"]["PatchedOrderStatusUpdate"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedOrderStatusUpdate"];
            };
        };
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_orders_accepted_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_orders_analytics_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_orders_create_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderCreate"];
                "multipart/form-data": components["schemas"]["OrderCreate"];
                "application/x-www-form-urlencoded": components["schemas"]["OrderCreate"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
        };
    };
    api_orders_declined_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_orders_dispatcher_my_orders_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_orders_dispatchers_available_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_orders_incoming_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_orders_shipped_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_orders_track_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_products_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_products_delete_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_products_images_delete_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
                image_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_products_images_upload_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_products_toggle_archive_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
        };
    };
    api_products_toggle_stock_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
        };
    };
    api_products_update_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["PatchedProductCreateUpdate"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedProductCreateUpdate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
        };
    };
    api_products_all_products_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"][];
                };
            };
        };
    };
    api_products_create_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["ProductCreateUpdate"];
                "application/x-www-form-urlencoded": components["schemas"]["ProductCreateUpdate"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
        };
    };
    api_products_featured_list: {
        parameters: {
            query?: {
                /** @description Number of products to return (default: 10) */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"][];
                };
            };
        };
    };
    api_products_list_retrieve: {
        parameters: {
            query?: {
                /** @description Whether to return archived products only */
                include_archived?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of products */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"][];
                };
            };
            /** @description Authentication credentials were not provided or are invalid */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User has not completed account setup */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_products_search_list: {
        parameters: {
            query?: {
                /** @description Maximum price */
                max_price?: number;
                /** @description Minimum price */
                min_price?: number;
                /** @description Sort by: price, -price, created_at, -created_at, name, -name */
                ordering?: string;
                /** @description Search query (searches name and description) */
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"][];
                };
            };
        };
    };
    api_products_search_store_list: {
        parameters: {
            query?: {
                /** @description Maximum price */
                max_price?: number;
                /** @description Minimum price */
                min_price?: number;
                /** @description Sort by */
                ordering?: string;
                /** @description Search query */
                q?: string;
            };
            header?: never;
            path: {
                store_slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"][];
                };
            };
        };
    };
    api_products_suggestions_retrieve: {
        parameters: {
            query: {
                /** @description Number of suggestions (default: 5) */
                limit?: number;
                /** @description Search query for suggestions */
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    api_schema_retrieve: {
        parameters: {
            query?: {
                format?: "json" | "yaml";
                lang?: "af" | "ar" | "ar-dz" | "ast" | "az" | "be" | "bg" | "bn" | "br" | "bs" | "ca" | "ckb" | "cs" | "cy" | "da" | "de" | "dsb" | "el" | "en" | "en-au" | "en-gb" | "eo" | "es" | "es-ar" | "es-co" | "es-mx" | "es-ni" | "es-ve" | "et" | "eu" | "fa" | "fi" | "fr" | "fy" | "ga" | "gd" | "gl" | "he" | "hi" | "hr" | "hsb" | "hu" | "hy" | "ia" | "id" | "ig" | "io" | "is" | "it" | "ja" | "ka" | "kab" | "kk" | "km" | "kn" | "ko" | "ky" | "lb" | "lt" | "lv" | "mk" | "ml" | "mn" | "mr" | "ms" | "my" | "nb" | "ne" | "nl" | "nn" | "os" | "pa" | "pl" | "pt" | "pt-br" | "ro" | "ru" | "sk" | "sl" | "sq" | "sr" | "sr-latn" | "sv" | "sw" | "ta" | "te" | "tg" | "th" | "tk" | "tr" | "tt" | "udm" | "ug" | "uk" | "ur" | "uz" | "vi" | "zh-hans" | "zh-hant";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.oai.openapi": {
                        [key: string]: unknown;
                    };
                    "application/yaml": {
                        [key: string]: unknown;
                    };
                    "application/vnd.oai.openapi+json": {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    store_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Unique slug identifying the merchant's store */
                store_slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Merchant store details and product list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        merchant?: {
                            business_name?: string;
                            business_description?: string;
                            /** Format: email */
                            business_email?: string;
                            /** Format: uri */
                            store_url?: string;
                            store_slug?: string;
                            full_name?: string | null;
                            /** Format: uri */
                            display_picture?: string | null;
                            phone_number?: string | null;
                            address?: string | null;
                        };
                        products?: components["schemas"]["Product"][];
                        total_products?: number;
                    };
                };
            };
            /** @description Store not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    store_retrieve_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_uuid: string;
                store_slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"];
                };
            };
        };
    };
}
